# Generated by Django 5.1.6 on 2025-02-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudantes',
            new_name='Estudante',
        ),
    ]
